### ISSUE TITLE
empty initial conditions

### ISSUE THREAD

**Issue by rheacangeo** [VulcanClimateModeling/fv3config#108]
The commit 0348a71f1cac9babe82cf23ae5a10c4345ebe14f (PR https://github.com/VulcanClimateModeling/fv3config/pull/104) seems to have removed support for 
initial_conditions: []
when making the run directory. The error is:

Traceback (most recent call last):
  File "venv/bin/write_run_directory", line 8, in <module>
    sys.exit(write_run_directory())
  File "venv/lib/python3.7/site-packages/fv3config/cli.py", line 49, in write_run_directory
    fv3config.write_run_directory(config, args.rundir)
  File venv/lib/python3.7/site-packages/fv3config/config/rundir.py", line 17, in write_run_directory
    current_date = get_current_date(config)
  File "venv/lib/python3.7/site-packages/fv3config/config/derive.py", line 64, in get_current_date
    coupler_res_filename = os.path.join(config["initial_conditions"], "coupler.res")
  File "/usr/local/opt/python/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
make: *** [setup_rundir] Error 1

It does work to make the run directory with 
initial_conditions: ""
So the choice is to add back support for [], or update the repos currently using older versions of fv3config that contain config files with empty initial conditions specified.

**Comment by oliverwm1** [comment]
This will be resolved by #107
